### ISSUE TITLE
[Warlock] Felguard wrong stats, Demonic knowledge , Fel vitality problem, expertise

### ISSUE THREAD

**Issue by danniellos94** [SallyWhitemane/Mograine#1088]
**Description:**
Felguard have wrong base stats demonic knowledge gives less than it should plus fel vitality is not working correctly with warlock stats. Also I will add that warlock pet should be expertise capped when master is hit capped - I'm pretty sure it doesn't work.

**How to reproduce:**

https://ibb.co/P637pT7
https://ibb.co/dK4qqWw
https://ibb.co/FbNk9bk
https://ibb.co/KLrMxvN
https://ibb.co/4PY1LhW
https://ibb.co/mGBdFqg

**How it should work:**
Ok so felguard stats should be - without talents
STR 314
AGI 90
STAM 328 * 1.15 fel vitality talent=377.2
INT 150 * 1.15 fel vitality talent=172.5
SPIRIT 209

On the first screen you can see I have 820 intellect that means pet should get 0.3 from that 820 * 0.3=246 * 1.15 fel vitality talent should be 282.9 but as you can see its 268 on the second screenshot.  (Check it how it does work for buffs also because I didn't test).

On the 5th screen you can see I have 975 stamina that means pet should get 0.75 from that 975 * 0.75=731.25* 1.15 fel vitality talent= 840.9, however as you can see on the last screenshot it's 780. (Check it how it does work for buffs also because I didn't test).

On 3rd screenshot you can see my spell power is 2046 without felguard and 2229 with felguard (183 difference). Demonic knowledge should give 12% spell damage of the total of stamina and demon's intellect.
1217(felguard stamina total)+455 (felguard intellect total)=1672*0.12 =200,64 - demonic knowledge gives less spell power than it should !

https://github.com/TrinityCore/TrinityCore/issues/7492
https://github.com/dalaranwow/dalaran-wow/issues/3237

**Comment by danniellos94** [comment]
Also cleave damage should be autoatack + 124 base + spell damage for me buffed only with fel armor it's 334 so the cleave damage should be min/max aa+124+334 but it's not.

**Comment by melezdev** [comment]
Another cleave bug:

Decription:
Warlock's felguard is having a hard time dealing with other pets due to avoidance reducing aoe damage even from pets / minions.

How it works:
Warlock's felguard has a cleave skill which hits a target plus his nearest ally. This skill is considered aoe, and in turn gets reduced by 90% when hitting other pets with avoidance skill. Its his hard hitting skill, capable of critting 2000 on training dummies, yet it only hits other pets for 50-100.

The problem will most likely be also present on any pet that does AOE, but I don't know of any others.

How it should work:
Avoidance is a pve skill and should only work in pve environment. Pets and minions should not trigger it. This would mean felguard doing around 100 dps more to enemy pets, depending on gear, defenses and talent configuration.
