### ISSUE TITLE
[DK - Blood ] Dancing Rune Weapon does not work properly

### ISSUE THREAD

**Issue by Bludlord** [SallyWhitemane/Mograine#1096]
**Description:**
DRW does not apply diseases 9/10 times when used. Sometimes what will happen is that diseases will be applied 3 times.
I have found that Icy Touch is guaranteed to apply two diseases while chains of ice and plague strike have a very low chance of applying diseases. What happens is the rune weapon does not even cast plague strike, or chains of ice most of the time. Sometimes the diseases are delayed by 2-3 seconds on appearing ( its not a visual bug from my UI, the dps meters both mine and an outside observer show that the diseases are in fact on), and sometimes the rune weapon diseases will disappear even with rune weapon still being active. You can find a decent display of what i mean in these two clips i did on target dummies:
https://www.youtube.com/watch?v=WVEDGOJZlGo
https://www.youtube.com/watch?v=fD3YDAag0Lk

Now the most logical answer is why this happens is because rune weapon does not swap targets hence it does not strike the extra abilities.  But even if you plague strike a secondary target, the rune weapon will continue just auto hitting the primary target without copying the plague strike. However, chains of ice does not apply double diseases no matter what target you hit with it.

This applies to every single death knight ability (HS,DS). This makes the class almost entirely unplayable. 

I am availiable at this discord tag if you have further questions thsaintx#7631

**How to reproduce:**
Self-explanatory really, find a target dummy and hit it

**How it should work:**
Rune weapon should always apply its own diseases ( what i mean by that its that it should hit its own version of CoA and plague strike which it does not) and scale the damage of its own ability hits by its own diseases. Now i can not positively confirm that the rune wepon heart strike/ blood strikes scale properly with its diseases but during limited testing it seems its doing about 10 percent less damage than it theoretically should.  I do not however stand entirely behind this due to the limitations of my testing and the way the ability works and calculates its damage based on snapshot.

**Comment by danniellos94** [comment]
Ok, so on retail dancing rune weapon at the beginning was just doing 50% of dk damage, and doing the same strikes as dk on targets. However blizzard changed it to snapshot mechanics which is indeed pretty bad for blood dk. 
They wanted to rune weapon to attack while dk is cced so it's better in pvp. 

However most of the dmg from rune weapon should come from used spells not autoattack, There were multiple bugs like drw being out of range of owner, attacking wrong target, changing target, not taking into account many talents (like might of mograine) and glyphs, tier set bonuses, sigils etc.

The snapshot mechanic is not needed, because if drw snapshot ur crit, ap, talents and glyphs it will do 50% damage of dk. The easiest way to make script work is just do to half of damage from ur spells while dancing rune is active and apply the diseases. 

And hence no, diseases from rune weapon doesnt increase damage of death strike, only heart strike. Also it's better to just do 50% of dk abilities and autoattack damage always it's easier to make it, really. Also less things can be bugged. I already reported this before and it's in progress.

https://github.com/SallyWhitemane/Mograine/issues/1058

**Comment by danniellos94** [comment]
I would suggest to close this report to not do unnecessary disorder. 

Gaga promised they will fix drw after ulduar so let's just wait for it.

**Comment by Bludlord** [comment]
> I would suggest to close this report to not do unnecessary disorder.
> 
> Gaga promised they will fix drw after ulduar so let's just wait for it.

K, ill close this then if theres another report for it. didnt see it
