### ISSUE TITLE
[Death Knight] Unholy DK Gargoyle cast

### ISSUE THREAD

**Issue by annaqtie** [SallyWhitemane/Mograine#554]
Unholy DK Gargoyle's cast is capped at a 1.5 seconds GCD

How to reproduce: cast summon gargoyle with enough haste to lower its spell cast below 1.5s. You will see pauses between casts that you do not see when the cast is above 1.5s caused by the gcd not scaling.

Gargoyle's cast gcd is supposed to scale down with its cast speed, so that the gcd is never longer than the spell cast. The entire strength of the ability is that is scales with the DK's haste/attack speed, this bug is a huge problem for unholy's single target dps. 

Proof from retail: http://www.worldoflogs.com/reports/m95i3mcw4ncujkb0/xe/?s=6297&e=7347&x=spell+%3D+%22Gargoyle+Strike%22

https://www.mmo-champion.com/threads/697868-Gargoyal-and-Haste?p=7382437&viewfull=1#post7382437

**Comment by alexspew** [comment]
Ticket needs to reopen.

From Rags on discord ::
If anything, gargoyle has been acting weirder since these changes
gargoyle was perfect before hand
This was a bug I tested and reported back in November and I can confirm that it's working properly
these changes need to be reverted

https://github.com/SallyWhitemane/Mograine/issues/26
Description: Currently, the gargoyle from Summon Gargoyle is capped at only 29 casts of Gargoyle Strike &amp; never interacts with a melee swing on this server. How to reproduce: I&#39;ve t...

Right now, if you summon gargoyle and the boss moves, the gargoyle moves too which is absolutely wrong. the gargoyle should stay in place and just keep casting
It was correct at launch
revert changes

**Comment by Rugsz** [comment]
^I'm "Rags" per the comment above. I'm willing to discuss details regarding Gargoyle scripting whenever. I'm Rugs#6239 on discord. I can clarify why this bug report was even sent in and why you need to revert these changes (the changes made on 02/05/2021). Gargoyle was true to 3.3.5 on launch on this server.

**Comment by sicknot1** [comment]
Range is also wonky, garg reactions are slow, they get stuck in doors, etc.
