### ISSUE TITLE
 [80] [Valduran the Stormborn](Part 1 of 2)

### ISSUE THREAD

**Issue by Ogbassist182** [SallyWhitemane/Mograine#561]
**Description:**
Quest in Storm Peaks. Have to use horn to summon allies to assist in killing named mob.

**How to reproduce:**
Blow the horn and it won't work.

**How it should work:**
The allies should activate mob so you can kill him.

**Comment by Ogbassist182** [comment]
This should be how it should work.

https://www.youtube.com/watch?v=jfFp621SDHc

**Comment by avarishd** [comment]
Can confirm, nothing happens when you use the [Bouldercrag's War Horn]. Also on top of that the mob (while in statis) should be doing a bladestorm-ish type of an animation.

Quest ID: 12984
NPC ID: 29368
Quest Item ID: 42419

Video reference (time stamped) with the event + his bladestorm animation prior to the War Horn being used: https://youtu.be/3VcxYiB-T-A?t=62

No event, no spinning animation (while in statis)
https://user-images.githubusercontent.com/46330494/106577426-04a5f300-6547-11eb-92a7-c660c487a942.mp4

**Comment by Ogbassist182** [comment]
Seems to be fixed now.

**Comment by Peppersprayz** [comment]
Nah it's still broken

**Comment by alexspew** [comment]
Hi, this is now working as intended.  Thanks!
