### ISSUE TITLE
Achievement "Lonely?"

### ISSUE THREAD

**Issue by Veresa** [SallyWhitemane/Mograine#661]
I used the item "Romantic Picnic Basket" in Dalaran and then I eat the item "Buttermilk Delight" with another person but the achiev hasn't been completed.

The achievement say: "Enjoy a Buttermilk Delight with someone in Dalaran at a Romanic Picnic during the Love is in the Air celebration", to reproduce it just do as it says.

This video shows how to do it:
https://www.youtube.com/watch?v=Xz1UGyaeY3Y

**Comment by cachocarne** [comment]
I know it's too late for this since the Love is in the Air event is over, but you need to keep in mind it's important to WAIT after clicking on the Romantic Picnic. Only a few seconds later, when you sit down and get the heart hovering above your head, is when you can eat the Buttermilk Delight to obtain the achievement.
