### ISSUE TITLE
Immolation aura bug

### ISSUE THREAD

**Issue by GitGudNubHub** [SallyWhitemane/Mograine#957]
Description: immolation aura gets turned off once the demon form ends
How to reproduce:use immolation aura right before the metamorphosis runs out
How it should work:every wotlk server ive played has the spell stay after the meta runs out.

**Comment by herbhenk** [comment]
this is working as intended dont change
on retail immolation aura also disapeared when meta ended
you can read about it here:
https://www.wowhead.com/forums/topic/metamorphosis-question-163379

**Comment by Vaxsysl** [comment]
Indeed, this is working as intended. When Metamorphosis expires, so do all demonic elements stop, including Immolation Aura. We can find more evidence than what @herbhenk posted, I was researching that myself in the past. Some players get an idea to get Glyph of Metamorphosis which extends the duration b 6sec, allowing 2nd Immolation Aura usage instead of single, and if it is bugged player gets two Immolation Auras, one running during demon form and another one just as it ends, but unfortunately that should not be the working case. Metamorphosis over - its all over.

Also, this bug report doesn't have evidence to support its claim. I'm surprised it got "fixed".
